version: '3.9'

services:
  mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=ecnirp
     - MYSQL_DATABASE=wordpress
    volumes:
     - database:/var/lib/mysql
    networks:
      - mynet

  go:
    image: princedevops/mycustomgoapp
    container_name: go
    ports:
      - "4000:4000"

  wordpress:
    image: princedevops/mycustomwordpressapp
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=ecnirp
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - mynet

  nextjs:
    image: princedevops/mycustomtsapp
    container_name: nextjs
    ports:
      - "3000:3000"

volumes:
  pgdata:

networks:
  mynet:
