name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: STAGING

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Go Docker image
        run: docker build -t ${{ vars.GO_DOCKER_IMAGE }} Go/

      - name: Build Nextjs Docker image
        run: docker build -t ${{ vars.TS_DOCKER_IMAGE }} NextJs/

      - name: Build Wordpress Docker image
        run: docker build -t ${{ vars.WORDPRESS_DOCKER_IMAGE }} Wordpress/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Go Docker image
        run: docker push ${{ vars.GO_DOCKER_IMAGE }}

      - name: Push Nextjs Docker image
        run: docker push ${{ vars.TS_DOCKER_IMAGE }}
        
      - name: Push Wordpress Docker image
        run: docker push ${{ vars.WORDPRESS_DOCKER_IMAGE }}
